# Generated by Django 5.0.1 on 2024-02-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_userworkout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userworkout",
            name="selected_exercises",
        ),
        migrations.CreateModel(
            name="SelectedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.exercise"
                    ),
                ),
                (
                    "user_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.userworkout",
                    ),
                ),
            ],
        ),
    ]
