# Generated by Django 5.0.1 on 2024-01-28 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_comment_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
