# Generated by Django 5.0.1 on 2024-02-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_userworkout_selected_exercises_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.PositiveIntegerField(default=12)),
                ("weight", models.PositiveIntegerField(default=12)),
                (
                    "selected_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.selectedexercise",
                    ),
                ),
            ],
        ),
    ]
