# Generated by Django 5.0.1 on 2024-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="arm_choice",
            field=models.CharField(
                choices=[
                    ("left_snug", "Left Arm (watch is snug to my wrist)"),
                    ("right_snug", "Right Arm (watch is snug to my wrist)"),
                    ("left_strap", "Left Arm (but I wear wrist straps)"),
                    ("right_strap", "Right Arm (but I wear wrist straps)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.CharField(default="12 Jan 2021", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
