# Generated by Django 5.0.1 on 2024-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_customuser_arm_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="height_measurement",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight_measurement",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
