# Generated by Django 5.0.1 on 2024-02-19 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_customuser_height_measurement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 2, 19, 11, 44, 26, 750335, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
