# Generated by Django 5.0.1 on 2024-02-19 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 19, 13, 23, 30, 279047, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
                verbose_name="first name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 19, 13, 23, 43, 850311, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
                verbose_name="last name",
            ),
            preserve_default=False,
        ),
    ]
