# Generated by Django 5.0.1 on 2024-02-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_customworkout_workoutgroup_workoutsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.workoutgroup",
            ),
        ),
    ]
