# Generated by Django 5.0.1 on 2024-02-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_workoutsession_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.workoutgroup"
            ),
        ),
    ]
