# Generated by Django 5.0.1 on 2024-02-22 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutgroup",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
